/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    clients: Client;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    stats: Stat;
    services: Service;
    industries: Industry;
    process: Process;
    offer: Offer;
    why: Why;
    faq: Faq;
    showreel: Showreel;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    process: ProcessSelect<false> | ProcessSelect<true>;
    offer: OfferSelect<false> | OfferSelect<true>;
    why: WhySelect<false> | WhySelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    showreel: ShowreelSelect<false> | ShowreelSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for screen readers and SEO.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * Client / case study name shown on the card and drawer.
   */
  title: string;
  /**
   * URL-safe identifier, e.g. "sundari-silks".
   */
  slug: string;
  /**
   * Small label above the title, e.g. "E-commerce · SEO".
   */
  tag?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Short teaser shown on the card and as the drawer fallback.
   */
  summary?: string | null;
  /**
   * Card thumbnail (16:9).
   */
  listingImage?: (number | null) | Media;
  /**
   * Large image at the top of the drawer. Falls back to the listing image.
   */
  coverImage?: (number | null) | Media;
  sections?:
    | {
        /**
         * Use the embed block to add iframes (YouTube, Figma, Loom, prototypes). Upload images directly in the editor.
         */
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role?: string | null;
  /**
   * Monogram shown in the avatar, e.g. "BG".
   */
  initials?: string | null;
  /**
   * Company logo shown in the footer. When empty, the initials monogram is shown instead.
   */
  logo?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logos shown in the "Trusted by" marquee. No logo → the name renders as a text wordmark.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * Optional. When empty, the name renders as a text wordmark.
   */
  logo?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit form submissions. Read-only record — do not edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone: string;
  message?: string | null;
  /**
   * Attribution captured at submit time.
   */
  tracking?: {
    pageUrl?: string | null;
    referrer?: string | null;
    ip?: string | null;
    userAgent?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    utmTerm?: string | null;
    utmContent?: string | null;
    gclid?: string | null;
    wbraid?: string | null;
    gbraid?: string | null;
    fbclid?: string | null;
    msclkid?: string | null;
    /**
     * All query params present at submit (catch-all).
     */
    params?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tag?: T;
  order?: T;
  summary?: T;
  listingImage?: T;
  coverImage?: T;
  sections?:
    | T
    | {
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  initials?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  tracking?:
    | T
    | {
        pageUrl?: T;
        referrer?: T;
        ip?: T;
        userAgent?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        utmTerm?: T;
        utmContent?: T;
        gclid?: T;
        wbraid?: T;
        gbraid?: T;
        fbclid?: T;
        msclkid?: T;
        params?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  headline: string;
  subhead?: string | null;
  primaryCtaLabel?: string | null;
  /**
   * e.g. "#services" or a full URL.
   */
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  /**
   * Query/result groups cycled by the hero search animation. Leave empty to use the built-in defaults.
   */
  searchPairs?:
    | {
        query: string;
        /**
         * First result is shown as "Top result".
         */
        results?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * Heading text before the accent word.
   */
  headingBefore?: string | null;
  /**
   * Highlighted (serif) word.
   */
  headingAccent?: string | null;
  /**
   * Heading text after the accent word.
   */
  headingAfter?: string | null;
  items?:
    | {
        /**
         * e.g. "₹"
         */
        prefix?: string | null;
        value: number;
        /**
         * Decimal places to animate to.
         */
        decimals?: number | null;
        /**
         * e.g. "%", "x", " days"
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Heading text before the accent word.
   */
  headingBefore?: string | null;
  /**
   * Highlighted (serif) word.
   */
  headingAccent?: string | null;
  /**
   * Heading text after the accent word.
   */
  headingAfter?: string | null;
  bands?:
    | {
        headingBefore?: string | null;
        headingAccent?: string | null;
        headingAfter?: string | null;
        body?: string | null;
        cards?:
          | {
              icon:
                | 'search'
                | 'chat'
                | 'sparkles'
                | 'gear'
                | 'megaphone'
                | 'share'
                | 'chart'
                | 'layout'
                | 'globe'
                | 'cart'
                | 'code'
                | 'pen'
                | 'bolt'
                | 'shield'
                | 'mobile';
              title: string;
              body?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  /**
   * Heading text before the accent word.
   */
  headingBefore?: string | null;
  /**
   * Highlighted (serif) word.
   */
  headingAccent?: string | null;
  /**
   * Heading text after the accent word.
   */
  headingAfter?: string | null;
  items?:
    | {
        name: string;
        line?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process".
 */
export interface Process {
  id: number;
  /**
   * Heading text before the accent word.
   */
  headingBefore?: string | null;
  /**
   * Highlighted (serif) word.
   */
  headingAccent?: string | null;
  /**
   * Heading text after the accent word.
   */
  headingAfter?: string | null;
  steps?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer".
 */
export interface Offer {
  id: number;
  /**
   * Heading text before the accent word.
   */
  headingBefore?: string | null;
  /**
   * Highlighted (serif) word.
   */
  headingAccent?: string | null;
  /**
   * Heading text after the accent word.
   */
  headingAfter?: string | null;
  offers?:
    | {
        title: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Button label.
         */
        cta?: string | null;
        href?: string | null;
        /**
         * Highlighted (primary background) card.
         */
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why".
 */
export interface Why {
  id: number;
  /**
   * Heading text before the accent word.
   */
  headingBefore?: string | null;
  /**
   * Highlighted (serif) word.
   */
  headingAccent?: string | null;
  /**
   * Heading text after the accent word.
   */
  headingAfter?: string | null;
  points?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * Heading text before the accent word.
   */
  headingBefore?: string | null;
  /**
   * Highlighted (serif) word.
   */
  headingAccent?: string | null;
  /**
   * Heading text after the accent word.
   */
  headingAfter?: string | null;
  items?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage showreel. Provide an uploaded video OR a video URL. The section is hidden on the site until one is set.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showreel".
 */
export interface Showreel {
  id: number;
  /**
   * Section heading (optional).
   */
  heading?: string | null;
  /**
   * Uploaded video file (mp4/webm). Takes priority over Video URL.
   */
  videoFile?: (number | null) | Media;
  /**
   * Or a video URL — a direct .mp4/.webm link, or a YouTube/Vimeo link.
   */
  videoUrl?: string | null;
  /**
   * Poster image shown before playback (used for uploaded/direct videos).
   */
  poster?: (number | null) | Media;
  /**
   * Autoplay muted on loop (uploaded/direct videos only).
   */
  autoplay?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  headline?: T;
  subhead?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  searchPairs?:
    | T
    | {
        query?: T;
        results?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  items?:
    | T
    | {
        prefix?: T;
        value?: T;
        decimals?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  bands?:
    | T
    | {
        headingBefore?: T;
        headingAccent?: T;
        headingAfter?: T;
        body?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  items?:
    | T
    | {
        name?: T;
        line?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process_select".
 */
export interface ProcessSelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offer_select".
 */
export interface OfferSelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  offers?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        cta?: T;
        href?: T;
        featured?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why_select".
 */
export interface WhySelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  points?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  headingBefore?: T;
  headingAccent?: T;
  headingAfter?: T;
  items?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showreel_select".
 */
export interface ShowreelSelect<T extends boolean = true> {
  heading?: T;
  videoFile?: T;
  videoUrl?: T;
  poster?: T;
  autoplay?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}